name: Benchmark Comment on PR

on:
    pull_request:
        paths:
            - 'src/**'
            - '!src/**/*.test.ts'
            - '!src/**/*.spec.ts'
    workflow_dispatch:
        inputs:
            pr_number:
                description: 'PR number to run benchmark on'
                required: false
                type: string

permissions:
    pull-requests: write

jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

            - uses: pnpm/action-setup@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run benchmark
              run: pnpm bench

            - name: Convert benchmark results to markdown
              run: |
                  node ./scripts/benchmark-to-md.mjs benchmark-result.json ${{ github.sha }} > benchmark-results.md

            - name: Create PR comment
              uses: actions/github-script@v6
              with:
                  script: |
                      const fs = await import('node:fs/promises');

                      const content = await fs.readFile('benchmark-results.md', 'utf8');
                      const finalContent = content +
                        '\n\n*Last updated by [GitHub Actions](https://github.com/' +
                        process.env.GITHUB_REPOSITORY + '/actions/runs/' +
                        process.env.GITHUB_RUN_ID + ')*';

                      let prNumber;
                      if (context.eventName === 'pull_request') {
                        prNumber = context.payload.pull_request.number;
                      } else if (context.payload.inputs?.pr_number) {
                        prNumber = parseInt(context.payload.inputs.pr_number, 10);
                      } else {
                        console.log('No PR number provided for workflow_dispatch event');
                        return;
                      }

                      const { data: comments } = await github.rest.issues.listComments({
                        ...context.repo,
                        issue_number: prNumber,
                      });

                      const existingComment = comments.find(comment =>
                        comment.body.includes('### Benchmark Results')
                      );

                      if (existingComment) {
                        await github.rest.issues.updateComment({
                          ...context.repo,
                          comment_id: existingComment.id,
                          body: finalContent,
                        });
                      } else {
                        await github.rest.issues.createComment({
                          ...context.repo,
                          issue_number: prNumber,
                          body: finalContent,
                        });
                      }
