name: Update Benchmark Results

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - '!src/**/*.test.ts'
            - '!src/**/*.spec.ts'
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: read

jobs:
    update-benchmark:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run benchmark
              run: pnpm bench

            - name: Convert benchmark results to markdown
              run: |
                  node ./scripts/benchmark-to-md.mjs benchmark-result.json ${{ github.sha }} true > BENCHMARK.md
                  pnpm run md:fix

            - name: Commit benchmark results
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add BENCHMARK.md

                  if git diff --staged --quiet; then
                    echo "No changes to commit"
                    exit 0
                  fi

                  git commit -m "📝 docs: update benchmark results [skip ci]"
                  git push
